export interface BrowseCar {
  make: string;
  model: string;
  yearRange: string;
  budgetTier: 5000 | 10000 | 15000 | 25000 | 35000;
  type: "sedan" | "suv" | "truck";
  reliabilityScore: number;
  avgPrice: number;
  nhtsaComplaints: number;
  topIssue: string | null;
  trimWarning: string | null;
  hiddenGem: boolean;
  hiddenGemNote: string | null;
}

export const browseCars: BrowseCar[] = [
  // ===== UNDER $5,000 =====
  {
    make: "Toyota",
    model: "Corolla",
    yearRange: "2008–2012",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 4500,
    nhtsaComplaints: 312,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Civic",
    yearRange: "2008–2011",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 4800,
    nhtsaComplaints: 487,
    topIssue: "Engine block cracks (2006–2009)",
    trimWarning: "Avoid 2006-2008 1.8L — block cracking issue",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "Mazda3",
    yearRange: "2010–2013",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 4200,
    nhtsaComplaints: 198,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Pontiac",
    model: "Vibe",
    yearRange: "2005–2010",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 3500,
    nhtsaComplaints: 142,
    topIssue: null,
    trimWarning: null,
    hiddenGem: true,
    hiddenGemNote: "It's a Toyota Matrix underneath — same 1.8L engine, same reliability, lower price because Pontiac badge.",
  },
  {
    make: "Toyota",
    model: "Camry",
    yearRange: "2005–2009",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 4600,
    nhtsaComplaints: 521,
    topIssue: "Excessive oil consumption (2007–2009 2.4L)",
    trimWarning: "2007-2009 2.4L engines can burn oil — check levels",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Fit",
    yearRange: "2007–2013",
    budgetTier: 5000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 4300,
    nhtsaComplaints: 164,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "RAV4",
    yearRange: "2006–2010",
    budgetTier: 5000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 4900,
    nhtsaComplaints: 378,
    topIssue: "Excessive oil consumption (2006-2008 2.4L)",
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Ford",
    model: "Ranger",
    yearRange: "2006–2011",
    budgetTier: 5000,
    type: "truck",
    reliabilityScore: 7,
    avgPrice: 4800,
    nhtsaComplaints: 246,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2005–2009",
    budgetTier: 5000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 4700,
    nhtsaComplaints: 289,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearRange: "2001–2004",
    budgetTier: 5000,
    type: "truck",
    reliabilityScore: 8,
    avgPrice: 4900,
    nhtsaComplaints: 195,
    topIssue: "Frame rust (pre-2004, recall covered)",
    trimWarning: "Check frame for rust — Toyota issued recall for 1995-2004 frames",
    hiddenGem: false,
    hiddenGemNote: null,
  },

  // ===== UNDER $10,000 =====
  {
    make: "Toyota",
    model: "Camry",
    yearRange: "2012–2015",
    budgetTier: 10000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 8500,
    nhtsaComplaints: 287,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Civic",
    yearRange: "2013–2015",
    budgetTier: 10000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 9200,
    nhtsaComplaints: 341,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "CX-5",
    yearRange: "2014–2016",
    budgetTier: 10000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 9800,
    nhtsaComplaints: 214,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Subaru",
    model: "Forester",
    yearRange: "2014–2016",
    budgetTier: 10000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 9500,
    nhtsaComplaints: 356,
    topIssue: "Excessive oil consumption",
    trimWarning: "2.5L boxer engines may burn oil — check levels before buying",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Corolla",
    yearRange: "2013–2016",
    budgetTier: 10000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 8800,
    nhtsaComplaints: 198,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "Mazda3",
    yearRange: "2014–2016",
    budgetTier: 10000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 8200,
    nhtsaComplaints: 178,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2012–2014",
    budgetTier: 10000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 9600,
    nhtsaComplaints: 267,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearRange: "2008–2012",
    budgetTier: 10000,
    type: "truck",
    reliabilityScore: 8,
    avgPrice: 9900,
    nhtsaComplaints: 221,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Kia",
    model: "Soul",
    yearRange: "2014–2016",
    budgetTier: 10000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 7800,
    nhtsaComplaints: 312,
    topIssue: "Engine bearing failure (2012-2016)",
    trimWarning: "Check for Theta II engine recall — some 2.0L models affected",
    hiddenGem: false,
    hiddenGemNote: null,
  },

  // ===== UNDER $15,000 =====
  {
    make: "Toyota",
    model: "Camry",
    yearRange: "2015–2018",
    budgetTier: 15000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 13500,
    nhtsaComplaints: 189,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Civic",
    yearRange: "2016–2018",
    budgetTier: 15000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 14200,
    nhtsaComplaints: 423,
    topIssue: "Oil dilution (1.5T turbo in cold climates)",
    trimWarning: "1.5T turbo can get oil dilution in cold climates — check for gas smell in oil",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "Mazda3",
    yearRange: "2015–2017",
    budgetTier: 15000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 12800,
    nhtsaComplaints: 156,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "RAV4",
    yearRange: "2014–2016",
    budgetTier: 15000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 14500,
    nhtsaComplaints: 278,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Subaru",
    model: "Forester",
    yearRange: "2015–2017",
    budgetTier: 15000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 13800,
    nhtsaComplaints: 298,
    topIssue: "Excessive oil consumption",
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2015–2016",
    budgetTier: 15000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 14800,
    nhtsaComplaints: 234,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "CX-5",
    yearRange: "2016–2018",
    budgetTier: 15000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 14200,
    nhtsaComplaints: 187,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearRange: "2013–2015",
    budgetTier: 15000,
    type: "truck",
    reliabilityScore: 8,
    avgPrice: 14900,
    nhtsaComplaints: 198,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  // Cars to AVOID in this tier
  {
    make: "Nissan",
    model: "Altima",
    yearRange: "2013–2016",
    budgetTier: 15000,
    type: "sedan",
    reliabilityScore: 3,
    avgPrice: 9800,
    nhtsaComplaints: 1842,
    topIssue: "CVT transmission failure",
    trimWarning: "Jatco CVT is a known failure point — expect $3,000+ replacement",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Jeep",
    model: "Compass",
    yearRange: "2014–2017",
    budgetTier: 15000,
    type: "suv",
    reliabilityScore: 3,
    avgPrice: 10500,
    nhtsaComplaints: 1256,
    topIssue: "Electrical system failures",
    trimWarning: "Known for stalling, electrical gremlins, and transmission issues",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Ford",
    model: "Focus",
    yearRange: "2012–2016",
    budgetTier: 15000,
    type: "sedan",
    reliabilityScore: 2,
    avgPrice: 7500,
    nhtsaComplaints: 3124,
    topIssue: "PowerShift dual-clutch transmission failure",
    trimWarning: "AUTOMATIC ONLY — the PowerShift DCT is catastrophically unreliable. Manual trans is fine.",
    hiddenGem: false,
    hiddenGemNote: null,
  },

  // ===== UNDER $25,000 =====
  {
    make: "Toyota",
    model: "Camry",
    yearRange: "2019–2021",
    budgetTier: 25000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 22500,
    nhtsaComplaints: 142,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Lexus",
    model: "ES 350",
    yearRange: "2017–2019",
    budgetTier: 25000,
    type: "sedan",
    reliabilityScore: 10,
    avgPrice: 24500,
    nhtsaComplaints: 67,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "CX-5",
    yearRange: "2019–2021",
    budgetTier: 25000,
    type: "suv",
    reliabilityScore: 9,
    avgPrice: 23200,
    nhtsaComplaints: 134,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Civic",
    yearRange: "2020–2021",
    budgetTier: 25000,
    type: "sedan",
    reliabilityScore: 8,
    avgPrice: 21800,
    nhtsaComplaints: 178,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Subaru",
    model: "Outback",
    yearRange: "2018–2019",
    budgetTier: 25000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 22000,
    nhtsaComplaints: 267,
    topIssue: "CVT hesitation",
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "RAV4",
    yearRange: "2019–2021",
    budgetTier: 25000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 24000,
    nhtsaComplaints: 198,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2019–2021",
    budgetTier: 25000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 23500,
    nhtsaComplaints: 342,
    topIssue: "Oil dilution (1.5T in cold climates)",
    trimWarning: "1.5T turbo oil dilution still present — less severe in 2019+",
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearRange: "2017–2019",
    budgetTier: 25000,
    type: "truck",
    reliabilityScore: 8,
    avgPrice: 24800,
    nhtsaComplaints: 187,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Hyundai",
    model: "Tucson",
    yearRange: "2016–2018",
    budgetTier: 25000,
    type: "suv",
    reliabilityScore: 4,
    avgPrice: 16500,
    nhtsaComplaints: 987,
    topIssue: "Engine seizure / recall",
    trimWarning: "Theta II engine recall — risk of engine fire and seizure",
    hiddenGem: false,
    hiddenGemNote: null,
  },

  // ===== UNDER $35,000 =====
  {
    make: "Toyota",
    model: "Camry",
    yearRange: "2022–2024",
    budgetTier: 35000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 28500,
    nhtsaComplaints: 78,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "CX-5",
    yearRange: "2021–2023",
    budgetTier: 35000,
    type: "suv",
    reliabilityScore: 9,
    avgPrice: 27800,
    nhtsaComplaints: 98,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "Civic",
    yearRange: "2022–2023",
    budgetTier: 35000,
    type: "sedan",
    reliabilityScore: 9,
    avgPrice: 26200,
    nhtsaComplaints: 112,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Lexus",
    model: "ES 350",
    yearRange: "2020–2022",
    budgetTier: 35000,
    type: "sedan",
    reliabilityScore: 10,
    avgPrice: 33500,
    nhtsaComplaints: 45,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "RAV4",
    yearRange: "2022–2024",
    budgetTier: 35000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 29800,
    nhtsaComplaints: 87,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2023–2024",
    budgetTier: 35000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 31200,
    nhtsaComplaints: 64,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Mazda",
    model: "CX-50",
    yearRange: "2023–2024",
    budgetTier: 35000,
    type: "suv",
    reliabilityScore: 8,
    avgPrice: 30500,
    nhtsaComplaints: 76,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearRange: "2020–2023",
    budgetTier: 35000,
    type: "truck",
    reliabilityScore: 8,
    avgPrice: 33000,
    nhtsaComplaints: 134,
    topIssue: null,
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
  {
    make: "Subaru",
    model: "Outback",
    yearRange: "2022–2024",
    budgetTier: 35000,
    type: "suv",
    reliabilityScore: 7,
    avgPrice: 29500,
    nhtsaComplaints: 156,
    topIssue: "Infotainment freezing",
    trimWarning: null,
    hiddenGem: false,
    hiddenGemNote: null,
  },
];

export const hiddenGems = [
  {
    make: "Ford",
    model: "Focus",
    yearRange: "2012–2016",
    note: "Manual transmission only — the PowerShift automatic is a disaster, but the manual gearbox is perfectly reliable. Huge price discount because of the auto's reputation.",
    reliabilityScore: 7,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearRange: "2017 LX",
    note: "The 2017 CR-V LX has the old 2.4L naturally aspirated engine, NOT the problematic 1.5T turbo. All the CR-V goodness without the oil dilution issue.",
    reliabilityScore: 8,
  },
  {
    make: "Pontiac",
    model: "Vibe",
    yearRange: "2003–2010",
    note: "It's literally a Toyota Matrix with a different badge. Same Corolla-based 1.8L engine, same transmission, same reliability — but thousands less because people don't realize it's a Toyota.",
    reliabilityScore: 9,
  },
];

export const budgetTiers = [
  { value: 5000 as const, label: "Under $5K", description: "Budget-friendly reliable picks" },
  { value: 10000 as const, label: "Under $10K", description: "Sweet spot for value" },
  { value: 15000 as const, label: "Under $15K", description: "Most popular budget" },
  { value: 25000 as const, label: "Under $25K", description: "Nearly new quality" },
  { value: 35000 as const, label: "Under $35K", description: "Like-new options" },
];
